//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTester.SharePointFtpService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.4guysfrompalmira.net/contracts/2013/04/04", ConfigurationName="SharePointFtpService.ISharePointFtpService")]
    public interface ISharePointFtpService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.4guysfrompalmira.net/contracts/2013/04/04/ISharePointFtpService/Open", ReplyAction="http://www.4guysfrompalmira.net/contracts/2013/04/04/ISharePointFtpService/OpenRe" +
            "sponse")]
        bool Open(string url, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.4guysfrompalmira.net/contracts/2013/04/04/ISharePointFtpService/List", ReplyAction="http://www.4guysfrompalmira.net/contracts/2013/04/04/ISharePointFtpService/ListRe" +
            "sponse")]
        string[] List(string currentFolder);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.4guysfrompalmira.net/contracts/2013/04/04/ISharePointFtpService/Change" +
            "Directory", ReplyAction="http://www.4guysfrompalmira.net/contracts/2013/04/04/ISharePointFtpService/Change" +
            "DirectoryResponse")]
        bool ChangeDirectory(string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.4guysfrompalmira.net/contracts/2013/04/04/ISharePointFtpService/Get", ReplyAction="http://www.4guysfrompalmira.net/contracts/2013/04/04/ISharePointFtpService/GetRes" +
            "ponse")]
        byte[] Get(string file);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISharePointFtpServiceChannel : ServiceTester.SharePointFtpService.ISharePointFtpService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SharePointFtpServiceClient : System.ServiceModel.ClientBase<ServiceTester.SharePointFtpService.ISharePointFtpService>, ServiceTester.SharePointFtpService.ISharePointFtpService {
        
        public SharePointFtpServiceClient() {
        }
        
        public SharePointFtpServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SharePointFtpServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SharePointFtpServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SharePointFtpServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Open(string url, string username, string password) {
            return base.Channel.Open(url, username, password);
        }
        
        public string[] List(string currentFolder) {
            return base.Channel.List(currentFolder);
        }
        
        public bool ChangeDirectory(string path) {
            return base.Channel.ChangeDirectory(path);
        }
        
        public byte[] Get(string file) {
            return base.Channel.Get(file);
        }
    }
}
